// Generated by CoffeeScript 2.3.2
var AfterBrunch, exec, sysPath;

sysPath = require('path');

({exec} = require('child_process'));

module.exports = AfterBrunch = (function() {
  class AfterBrunch {
    constructor(config) {
      var ref, ref1;
      this.config = config;
      this.conf = (ref = this.config.plugins.afterBrunch) != null ? ref : {};
      this.commands = (ref1 = this.conf.commands) != null ? ref1 : [];
    }

    onCompile(generatedFiles) {
      var command, doRun, i, len, po, ref;
      po = this.conf.productionOnly === true ? true : false;
      doRun = po && !(process.env.NODE_ENV === 'production') ? false : true;
      if (doRun) {
        ref = this.commands;
        for (i = 0, len = ref.length; i < len; i++) {
          command = ref[i];
          exec(command, function(error, stdout, stderr) {
            if (stdout) {
              console.log(stdout);
            }
            if (error) {
              console.log(error.message);
            }
            if (stderr) {
              return console.log(stderr);
            }
          });
        }
      }
    }

  };

  AfterBrunch.prototype.brunchPlugin = true;

  return AfterBrunch;

}).call(this);

